# NumPy Exercises

Solve the following exercises and submit the notebook via Canvas.

In [2]:
import numpy as np

### NaN and infinity

NumPy (and other computer languages/libraries) have a special value called `NaN` ([Not a Number](https://en.wikipedia.org/wiki/NaN)).
NaN is the result of various arithmetic operations, e.g. 0/0, $-\infty + \infty$.

In NumPy, NaN is represented as `np.nan`.  NaN satisfies the following properties:

* Comparisons of NaN with a number x using one of the operators =, <, >, >=, and <= is always False.  Consequently, x != NaN is always True.

* Any arithmetic operation involving a NaN leads to a NaN 

Infinity is represented using `np.inf`, and negative infinity is `-np.inf`.

* Experiment with NaN and infinity and convince yourself that the results of the following operations make sense to you:

```Pytnon
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - 1
```

In [3]:
print("0 * np.nan --->", 0 * np.nan) # "nan" stands for not a number, so it will return nan
print("np.nan == np.nan --->",np.nan == np.nan) # definition of nan which nan not being equal to nan
print("np.isnan(np.nan) --->",np.isnan(np.nan)) # testing the element if it is NaN or not 
print("np.inf > np.nan --->",np.inf > np.nan) # "nan" stands for not a number, so it will return false
print("np.nan - 1 --->", np.nan - 1) # "nan" stands for not a number, so it will return nan

0 * np.nan ---> nan
np.nan == np.nan ---> False
np.isnan(np.nan) ---> True
np.inf > np.nan ---> False
np.nan - 1 ---> nan


### Creating arrays

* Create a 3x3 matrix with the integer values from 0 to 8.  Do this by creating a one dimensional array and converting it to a two dimensional array using the [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function.

In [4]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


* Create the same 3x3 matrix and have the end result be a floating point array with a dtype `float64`.

In [5]:
a = np.arange(0,9,dtype ='float').reshape(3,3)
print(a,a.dtype )

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] float64


* Create a vector (i.e. one dimensional array) of length 10 with random values between 0 and 1.

In [6]:
#inclusive 0 and 1
x = np.linspace(0,1,10,endpoint=True)
print("Inclued 0 and 1: ", x)
print()
#exclusive o and 1
y = np.linspace(0,1,12,endpoint=True)[1:-1]
print("Exclued 0 and 1: ", y)

Inclued 0 and 1:  [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Exclued 0 and 1:  [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


* Create a 10x10 array with 1 on the border and 0 inside.

In [7]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


* For an integer $n$, create an array of length $3n$ filled with the cyclic pattern 1, 2, 3.  For example, for $n=2$, the resulting array should be ```[1,2,3,1,2,3]```.

In [13]:
def repeat(n):
  arr= np.array([1,2,3])
  c = np.tile(arr,n)
  return c

print(repeat(2))

[1 2 3 1 2 3]


### Slices

Describe the effect of each of the following slices of the following two-dimensional array, i.e. matrix:

```Python
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Slice 1:
```Python
a2d[0]
```

*answer:  the first row of the matrix*  

This is an example to illustrate what we are looking for.

Slice 2:
```Python
a2d[1, :2]
```

*answer: read the second row, from column 0(included) to 2(excluded)*

Slice 3:
```Python
a2d[:, -1]
```

answer: read each row but get the last column of number from each row

Slice 4:
```Python
a2d[:, 1:]
```

*answer: read from column index 1 to the last index in each row*

Slice 5:
```Python
a2d[:,:]
```

*answer: read each row and each column of matrix*

* Replace all negative elements of the following array with the value 0.  This can be done with a single command! (Hint:  Boolean indexing).

In [9]:
a = np.array([-1, 3, -2, -3, 5, 6, -2])
# your code here
a[a<0] = 0
a

array([0, 3, 0, 0, 5, 6, 0])

* Write a command that replaces all NaN values with 0 in the following array.  Use [np.isnan](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html) with Boolean indexing.

In [10]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[np.isnan(a)] = 0
a

array([1., 2., 3., 0., 5., 6., 7., 0.])

Here's a more challenging exercise that you can solve using slices:

* Create a 8x8 matrix that looks like this:

```Python
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
```

Hint:  even and odd numbered rows each are filled with the same pattern.


In [11]:
#Create a 8x8 matrix 
m = np.ones((8,8),dtype = int)
m[::2,::2] = 0
m[1::2,1::2] = 0
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


* Given the two dimensional array bellow, write code to compute the mean value of each column and display the result.  *Do not use for loops!*

In [12]:
# computing column means of a 2d array:

a = np.array([[17.53, 18.55, 18.18, 10.8 , 10.08],
       [ 6.64, 15.78, 14.51, 12.4 , 14.6 ],
       [14.67,  2.02, 10.34,  3.79,  6.73],
       [12.61,  5.4 , 19.07, 13.76, 15.39],
       [ 1.82,  7.79,  5.41, 20.  , 18.17],
       [10.01,  8.88, 17.27,  1.73, 13.64]])
means = a.mean(axis=0)
print(means)


[10.54666667  9.73666667 14.13       10.41333333 13.10166667]
